# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YhBSZd_6WdYpJaiU45eVkl8uAUvcLNF8
"""

# Commented out IPython magic to ensure Python compatibility.
# Исследование данных о покемонах

## Импорт библиотек и загрузка данных
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display

# Настройка отображения графиков
plt.style.use('ggplot')  # Изменено с 'seaborn' на доступный стиль
plt.rcParams['figure.figsize'] = (10, 6)
# %matplotlib inline


df = pd.read_csv('pokemon.csv')
df = pd.DataFrame()

if not df.empty:
    # Просмотр первых строк данных
    display(df.head())

    # Информация о данных
    display(df.info())

    # Описание числовых столбцов
    display(df.describe())

    # Проверка на пропуски
    display(df.isnull().sum())
else:
    print("Данные не загружены, анализ невозможен.")

# Заполнение пропусков в type2
df['type2'] = df['type2'].fillna('None')

# Преобразование столбцов с множителями урона
against_cols = [col for col in df.columns if col.startswith('against_')]
for col in against_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Создание категориальных переменных
df['generation'] = df['generation'].astype('category')
df['is_legendary'] = df['is_legendary'].astype('bool')

# Распределение покемонов по поколениям
plt.figure(figsize=(10, 6))
sns.countplot(x='generation', data=df)
plt.title('Распределение покемонов по поколениям')
plt.xlabel('Поколение')
plt.ylabel('Количество')
plt.show()

"""Наибольшее количество покемонов создано в 1-м поколении (около 150)

В последующих поколениях количество новых покемонов уменьшается

6-е поколение содержит наименьшее число покемонов (около 70)

Видна тенденция к сокращению количества новых покемонов в каждом последующем поколении
"""

# Распределение покемонов по типам
plt.figure(figsize=(14, 8))
type_counts = pd.concat([df['type1'], df['type2'].replace('None', np.nan)]).dropna().value_counts()
sns.barplot(x=type_counts.index, y=type_counts.values)
plt.title('Распределение покемонов по типам')
plt.xlabel('Тип')
plt.ylabel('Количество')
plt.xticks(rotation=45)
plt.show()

"""Water (вода) — самый распространенный тип покемонов

Normal (обычный) и Grass (трава) занимают второе и третье места по популярности

Наименее распространенные типы — Ice (лед), Fairy (фея) и Flying (летающий)

Большинство покемонов имеют двойной тип (type2 не равен 'None')
"""

# Топ-10 покемонов по общей силе (base_total)
top_total = df.nlargest(10, 'base_total')[['name', 'type1', 'type2', 'base_total', 'is_legendary']]
display(top_total)

# Визуализация
plt.figure(figsize=(12, 6))
sns.barplot(x='name', y='base_total', data=top_total, hue='is_legendary', dodge=False)
plt.title('Топ-10 покемонов по общей силе')
plt.xlabel('Покемон')
plt.ylabel('Общая сила')
plt.xticks(rotation=45)
plt.legend(title='Легендарный')
plt.show()

"""Все топ-10 позиций занимают легендарные покемоны

Mewtwo и Rayquaza — абсолютные лидеры по базовой силе

Разница между первым и десятым местом составляет около 150 пунктов (780 vs 630)

Большинство сильнейших покемонов относятся к типам Psychic, Dragon или их комбинациям
"""

# Топ-5 покемонов по атаке
top_attack = df.nlargest(5, 'attack')[['name', 'type1', 'type2', 'attack', 'is_legendary']]
display(top_attack)

# Топ-5 покемонов по защите
top_defense = df.nlargest(5, 'defense')[['name', 'type1', 'type2', 'defense', 'is_legendary']]
display(top_defense)

# Топ-5 покемонов по скорости
top_speed = df.nlargest(5, 'speed')[['name', 'type1', 'type2', 'speed', 'is_legendary']]
display(top_speed)

"""# Топ-5 покемонов по атаке

Покемоны с самой высокой атакой преимущественно физического типа (Fighting, Dragon)

Deoxys (Attack Forme) имеет экстремально высокий показатель атаки (180)

Разрыв между первым и пятым местом значительный (180 vs 130)
# Топ-5 покемонов по защите

Shuckle имеет аномально высокий показатель защиты (230)

Остальные топовые защитники имеют показатели в диапазоне 140-160

Многие защитные покемоны относятся к типам Steel или Rock
# Топ-5 покемонов по скорости

Deoxys (Speed Forme) — абсолютный лидер по скорости (180)

Большинство быстрых покемонов относятся к типам Electric или Flying

Разрыв между первым и пятым местом значительный (180 vs 130)
"""

# Количество легендарных покемонов
legendary_counts = df['is_legendary'].value_counts()
display(legendary_counts)

# Визуализация
plt.figure(figsize=(6, 6))
plt.pie(legendary_counts, labels=['Обычные', 'Легендарные'], autopct='%1.1f%%')
plt.title('Доля легендарных покемонов')
plt.show()

"""Легендарные покемоны составляют около 8% от общего числа

Основная масса покемонов (92%) — обычные

Такое соотношение соответствует игровой механике, где легендарные покемоны редки
"""

# Средние характеристики легендарных и обычных покемонов
legendary_stats = df.groupby('is_legendary')[['hp', 'attack', 'defense', 'sp_attack', 'sp_defense', 'speed', 'base_total']].mean()
display(legendary_stats)

# Визуализация
plt.figure(figsize=(12, 6))
sns.heatmap(legendary_stats.T, annot=True, cmap='YlOrRd', fmt='.1f')
plt.title('Средние характеристики легендарных и обычных покемонов')
plt.show()

"""Легендарные покемоны превосходят обычные по всем характеристикам

Наибольшая разница наблюдается в Special Attack (≈90 vs ≈65)

Наименьшая разница — в HP (≈90 vs ≈70)

Общая сила (base_total) у легендарных в среднем на 40% выше
"""

# Легендарные покемоны по типам
legendary_by_type = df[df['is_legendary']].groupby('type1').size().sort_values(ascending=False)
display(legendary_by_type)

# Визуализация
plt.figure(figsize=(12, 6))
sns.barplot(x=legendary_by_type.index, y=legendary_by_type.values)
plt.title('Количество легендарных покемонов по типам')
plt.xlabel('Тип')
plt.ylabel('Количество')
plt.xticks(rotation=45)
plt.show()

"""Больше всего легендарных покемонов среди Psychic (психических) типов

Dragon (драконы) и Flying (летающие) занимают второе и третье места

Некоторые типы (например, Poison, Bug) почти не представлены среди легендарных
"""

# Средняя сила покемонов по поколениям
generation_stats = df.groupby('generation')['base_total'].agg(['mean', 'median', 'count'])
display(generation_stats)

# Визуализация
plt.figure(figsize=(12, 6))
sns.boxplot(x='generation', y='base_total', data=df)
plt.title('Распределение силы покемонов по поколениям')
plt.xlabel('Поколение')
plt.ylabel('Общая сила')
plt.show()

"""Средняя сила покемонов остается стабильной во всех поколениях

3-е поколение имеет наибольший разброс показателей силы

В каждом поколении есть выбросы — как очень сильные, так и очень слабые покемоны
"""

# Топ-3 покемона каждого поколения по силе
top_by_generation = df.groupby('generation').apply(lambda x: x.nlargest(3, 'base_total')[['name', 'type1', 'type2', 'base_total', 'is_legendary']])
display(top_by_generation)

# Связь роста и силы
plt.figure(figsize=(10, 6))
sns.scatterplot(x='height_m', y='base_total', hue='is_legendary', data=df)
plt.title('Связь роста покемона и его силы')
plt.xlabel('Рост (м)')
plt.ylabel('Общая сила')
plt.show()

# Связь веса и силы
plt.figure(figsize=(10, 6))
sns.scatterplot(x='weight_kg', y='base_total', hue='is_legendary', data=df)
plt.title('Связь веса покемона и его силы')
plt.xlabel('Вес (кг)')
plt.ylabel('Общая сила')
plt.show()

"""# Связь роста и силы

Общая тенденция: чем крупнее покемон, тем он сильнее

Однако есть много исключений — небольшие покемоны с высокой силой

Легендарные покемоны чаще крупнее обычных

# Связь веса и силы

Наблюдается слабая положительная корреляция между весом и силой

Самые тяжелые покемоны (>500 кг) имеют средние показатели силы

Некоторые легкие покемоны (<10 кг) могут быть очень сильными
"""

# Матрица корреляций
corr_matrix = df[['hp', 'attack', 'defense', 'sp_attack', 'sp_defense', 'speed', 'base_total', 'height_m', 'weight_kg']].corr()

# Визуализация
plt.figure(figsize=(12, 8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', center=0)
plt.title('Матрица корреляций характеристик покемонов')
plt.show()

"""Наибольшая корреляция: между base_total и attack/sp_attack

Speed (скорость) слабо коррелирует с другими характеристиками

HP (здоровье) имеет умеренную корреляцию с defense/sp_defense

Вес и рост слабо связаны с боевыми характеристиками

# Ключевые выводы:
Легендарные покемоны значительно сильнее обычных - их средняя общая сила почти в 1.5 раза выше. Больше всего легендарных покемонов среди типов Psychic, Dragon и Flying.

Самые сильные покемоны (по base_total) - это в основном легендарные, за исключением Slaking и Garchomp. Абсолютный лидер - Mewtwo с показателем 780.

Поколения покемонов имеют схожие средние показатели силы, хотя 1-е поколение показывает немного более высокие значения. В каждом поколении есть свои топовые покемоны.

Типы покемонов: Наиболее распространенные типы - Water и Normal. Некоторые типы (например, Ice, Fairy) встречаются реже, но могут быть более сильными в среднем.

Физические параметры: Существует слабая положительная корреляция между размером/весом покемона и его силой, но есть много исключений - маленькие покемоны могут быть очень сильными.

Характеристики: Наибольшая корреляция с общей силой наблюдается у attack и sp_attack, что говорит о важности атакующих характеристик.

Специализация: Некоторые покемоны демонстрируют экстремальные значения по отдельным характеристикам (например, Deoxys по скорости, Shuckle по защите).
"""